Misc changes
quarkiverse/quarkus-rabbitmq-client pull request #138
Opened 2022-12-15 10:22 UTC by SpeedsterF2

Updated to Quarkus 2.14.3 + some trivial changes

2022-12-16 09:48 UTC, bpasson commented
Thanks for submitting a PR. I will review it and if all checks out accept it.

2023-01-26 08:21 UTC, SpeedsterF2 commented
rebased PR on current master

2023-02-02 14:58 UTC, bpasson commented
@SpeedsterF2 can you have a look at the review comment?

2023-02-03 16:17 UTC, SpeedsterF2 commented
> @SpeedsterF2 can you have a look at the review comment?

Sorry, i do not konw where to look for comments added to the PR. Maybe that is just due to me being used to bitbucket.

2023-02-06 08:44 UTC, bpasson commented
@SpeedsterF2 See the files tab when logged in to your account. You should see the comments then. https://github.com/quarkiverse/quarkus-rabbitmq-client/pull/138/files

2023-02-06 14:14 UTC, SpeedsterF2 commented
> @SpeedsterF2 See the files tab when logged in to your account. You should see the comments then. https://github.com/quarkiverse/quarkus-rabbitmq-client/pull/138/files

I do not see any. 
![grafik](https://user-images.githubusercontent.com/38556808/216994289-3af341ac-8d21-4bed-888b-4c7e35e74ecc.png)

2023-02-07 07:30 UTC, bpasson requested changes

2023-02-07 07:31 UTC, bpasson commented on runtime/src/main/java/io/quarkiverse/rabbitmqclient/RabbitMQClients.java
> +            try {
@SpeedsterF2 do you see them now? The comments got stuck on pending it seemed.

2023-02-07 10:06 UTC, SpeedsterF2 commented on runtime/src/main/java/io/quarkiverse/rabbitmqclient/RabbitMQClients.java
> +            try {
Yeahr, now I see your comment!

2023-04-13 07:19 UTC, bpasson commented
@SpeedsterF2 I am closing the PR as it has diverged from the master branch and I am cleaning up to move to Quarkus 3.

2023-04-13 07:19 UTC, closed without merging

2023-04-19 12:57 UTC, SpeedsterF2 commented
OK,  I did not have time to work on this, lets reboot when v3 is out