#278 Feature add config max inbound message body size
quarkiverse/quarkus-rabbitmq-client pull request #279
Opened 2024-11-04 10:10 UTC by andyhan

Add Client Configuration maxInboundMessageBodySize for RabbitMQ ConnectionFactory, the Default value is 64 MiB

2024-11-05 15:04 UTC, bpasson commented
@andyhan thank you for taking time to submit this PR, I'm fine with the change, but could you rebase on main and squash to a single commit?

2024-11-05 15:05 UTC, bpasson requested changes
Please squash to a single commit.

2024-11-06 02:44 UTC, andyhan commented
> @andyhan Thank you for taking time to submit this PR, I'm fine with the change, could you please squash the PR to a single commit.

Done.

2025-01-08 07:38 UTC, bpasson approved these changes

2025-01-08 07:38 UTC, merged

2025-01-08 07:41 UTC, bpasson commented
@all-contributors please add @andyhan for code

2025-01-21 07:27 UTC, bpasson commented
fixes #278